"""empty message

Revision ID: 76735a40b3f2
Revises: 7b7694002a75
Create Date: 2025-07-15 16:02:33.215079

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76735a40b3f2"
down_revision = "7b7694002a75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meals",
        sa.Column(
            "plate_identifier",
            sa.String(length=255),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    script_path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "sql",
            "76735a40b3f2" + ".sql",
        )
    )
    if os.path.exists(script_path):
        with open(script_path, "r") as f:
            script_content = f.read()

        conn = op.get_bind()
        if conn.dialect.name == "sqlite":

            conn.connection.executescript(script_content)
        else:
            op.execute(script_content)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals", "plate_identifier")
    # ### end Alembic commands ###
